### ISSUE TITLE
Add missing Subgraph Entity/Field descriptions

### ISSUE THREAD

**Issue by filipv-eth** [jbx-protocol/juice-docs-v2#104]
Add missing descriptions to `/docs/dev/subgraph/entities.md` (both entities and fields).

**Comment by peripheralist** [comment]
I'm wondering if it'd be better to rely on the subgraph schema found in the playground here https://thegraph.com/explorer/subgraph?id=FVmuv3TndQDNd2BWARV8Y27yuKKukryKXPzvAS5E7htC&view=Playground, or in the schema.graphql on github, instead of duplicating it in the docs. Otherwise we'll need to maintain it here in the docs

wdyt @Data-Nexus ?

**Comment by Data-Nexus** [comment]
The best would be if we were able to pull the entities directly from the latest version deployed to the subgraph that way the docs dynamically update as changes are made. This would also make docs projects for other subgraphs way easier as well, not sure exactly how to do that though. Any ideas?

**Comment by filipv-eth** [comment]
How would you two feel about removing the field tables, and making this page one table? It would include entity names, descriptions, and links to the appropriate page on the playground. We can also include a note telling people to search the docs or join the Peel Discord if they have questions about individual fields.

**Comment by peripheralist** [comment]
I think I'm in favor of pointing to the graphql.schema on github for now. Anyone interested in the schema is prolly gonna have some dev chops anyway and would be cool with (if not prefer to be) looking at the code. Love @Data-Nexus 's idea of auto-updating, but ideally we'd wanna tie that to whenever a new subgraph version is published, which I don't have any leads on how to do.

If any devs in the future are requesting to have it in the docs then I'd be down to revisit

**Comment by Data-Nexus** [comment]
I'll ask around. Obviously it populates in the playground, so there's a way to do it. No clue what that entails currently though.

**Comment by filipv-eth** [comment]
Closing this for now
