### ISSUE TITLE
Fix links in docs

### ISSUE THREAD

**Issue by filipv-eth** [jbx-protocol/juice-docs-v2#4]
Many links are broken due to the new file structure

**Comment by i001962** [comment]
Made PR #10 for changes in docs section protocol-v1, 
reviewed: All other sections except protocol-v2. 

Question on page: [create-a-project/reconfiguration](https://github.com/jbx-protocol/juice-docs/blob/a7b7dfe56164900300c2a9446c3db9389eaf005c/getting-started/create-a-juicebox-project/reconfiguration.md?plain=1#L12)
Should the 'interface' link which is currently 
https://github.com/jbx-protocol/juice-contracts-v1/blob/05828d57e3a27580437fc258fe9041b2401fc044/contracts/FundingCycles.sol
be updated and if so, to what?

**Comment by filipv-eth** [comment]
Links all fixed. Closing this for now.
