### ISSUE TITLE
Add search

### ISSUE THREAD

**Issue by filipv-eth** [jbx-protocol/juice-docs-v2#6]

**Comment by i001962** [comment]
Any preferences on search packages to user here? A bit light on the requirements but figuring multi-language support, no paid services, no additional index servers to manage,... what else?

After reading this
https://docusaurus.io/community/resources#search
I prototyped search using 
https://github.com/praveenn77/docusaurus-lunr-search
which seems quite straight forward.

<img width="1115" alt="image" src="https://user-images.githubusercontent.com/1039388/160303288-ddfad851-32e4-44c4-9a9a-1ff488e88e50.png">

Let me know if directionally this is ok and if so I will PR for your consideration.

**Comment by i001962** [comment]
For the case you just want to add this and skip the pr

1- yarn add docusaurus-lunr-search 
2- update docusauraus.config yarn 
<img width="678" alt="image" src="https://user-images.githubusercontent.com/1039388/160303886-f3b9e85b-0e74-433e-b724-095bb8bd64bd.png">
Note - I had to turn brokenlinks into warning to get this to work with repo in current wip status
3 - must yarn build && yarn run serve to have a working index as it's generated at build time not dev time

**Comment by filipv-eth** [comment]
> Any preferences on search packages to user here? A bit light on the requirements but figuring multi-language support, no paid services, no additional index servers to manage,... what else?
> 
> After reading this https://docusaurus.io/community/resources#search I prototyped search using https://github.com/praveenn77/docusaurus-lunr-search which seems quite straight forward.
> 
> <img alt="image" width="1115" src="https://user-images.githubusercontent.com/1039388/160303288-ddfad851-32e4-44c4-9a9a-1ff488e88e50.png">
> 
> Let me know if directionally this is ok and if so I will PR for your consideration.

This looks great! My original plan was to follow along with the guide [here](https://docusaurus.io/docs/search) for adding Algolia DocSearch, which is officially supported. However, it may take some time for an application to go through. I'll leave the final choice up to you!

**Comment by filipv-eth** [comment]
Search bar isn't working on my local deploy. Stuck on "loading..."

**Comment by i001962** [comment]
It will only work AFTER a build. Annoying but 🤷‍♂️ 
So yarn run build && yarn run serve IIRC

**Comment by filipv-eth** [comment]
> It will only work AFTER a build. Annoying but man_shrugging So yarn run build && yarn run serve IIRC

Confirmed! Thanks again for your help, going to close this issue.
