### ISSUE TITLE
Need Bug Bounty landing page

### ISSUE THREAD

**Issue by nnnnicholas** [jbx-protocol/juice-docs-v2#73]
Immune.fi has asked for where to direct participants in JB protocol bug bounty. 

The page should be located at info.juicebox.money/bugbounty

The page should include a link to the forthcoming ImmuneFi bounty page, as well as who/how to get in touch to disclose a bug directly.

**Comment by filipv-eth** [comment]
Closing this for now, as the immune.fi contest is being delayed until the results of the c4a contest are remediated.
