### ISSUE TITLE
Broken link JBProjects.ownerOf()

### ISSUE THREAD

**Issue by nnnnicholas** [jbx-protocol/juice-docs-v2#86]
The link to JBProjects.ownerOf is broken here 

> Launching a project will mint a new NFT in the [`JBProjects`](/dev/api/contracts/jbprojects/README.md) contract. The owner can be found using [`JBProjects.ownerOf(...)`](https://docs.openzeppelin.com/contracts/3.x/dev/api/token/erc721#IERC721-ownerOf-uint256-).

in https://info.juicebox.money/dev/api/contracts/jbprojects/

1. Should it link to v3 or v4 of OZ? If v4, then this is the correct link https://docs.openzeppelin.com/contracts/4.x/api/token/erc721#IERC721-ownerOf-uint256-
2. I found it a little weird that the Read methods don't list the ownerOf method, but I understand that it's because they're inherited. Means searches for `JBProjects.ownerOf` don't turn up the JBProjects docs page. I understand the reasoning for not listing all the inherited read/write fns, but does make it trickier for people like Kevin:
 
<img width="581" alt="image" src="https://user-images.githubusercontent.com/1418561/178802617-1dc2a106-0b9f-440d-b80d-4ebf19f178aa.png">

cc @filipv-eth @mejango

**Comment by filipv-eth** [comment]
Fixed!
