### ISSUE TITLE
Review that OZ links all point to v4 docs 

### ISSUE THREAD

**Issue by nnnnicholas** [jbx-protocol/juice-docs-v2#87]
JB V2 uses OpenZeppelin v4 (see https://github.com/jbx-protocol/juice-contracts-v2/blob/main/package.json#L17)

Would be a good idea to sweep the docs to make sure we're not making any references to other versions of the OZ docs (I caught one on the JBProjects page #86).

**Comment by nnnnicholas** [comment]
main issue i'm noticing all over is OZ changed their docs route from 
`https://docs.openzeppelin.com/contracts/4.x/dev/api/...` to 
`https://docs.openzeppelin.com/contracts/4.x/api/...`

maybe @filipv-eth knows some crazy vim to fix this all over the joint 📿

**Comment by filipv-eth** [comment]
got you bruv https://github.com/jbx-protocol/juice-docs-v2/commit/d8739d10b4ca72b197a56c70965ec6931a9055fc
